format_version: 10
pipelines:
  Test-maria:
    group: AT20-maria
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-eebe0ef:
        git: https://github.com/AT20-DevOps/AT20_COMPILER_SERVICES.git
        username: Marseonji
        shallow_clone: false
        auto_update: true
        branch: task10-mh
        encrypted_password: AES:LJ4IAUFK4W+7NrC9EtW+2g==:zIDUwoH7olFG3z9p14+WfA==
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources:
            - ubuntu 
            tasks:
            - script: |
                npm install
                npm test
          code-coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code_inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - exec:
                arguments:
                - sonar-scanner command here
                command: echo
                run_if: passed
