format_version: 10
pipelines:
  Test1:
    group: at20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-de9e633:
        git: https://github.com/AT20-DevOps/AT20_COMPILER_SERVICES.git
        shallow_clone: false
        auto_update: true
        branch: task10-cj
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit_tests:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script: |
                npm install
                npm run test
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Code_coverage
                command: echo
                run_if: passed
    - Code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sonar-scanner command here
                command: echo
                run_if: passed
