format_version: 10
pipelines:
  Test1:
    group: at20
    template: pipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0b6196e:
        git: https://github.com/AT20-DevOps/AT20_COMPILER_SERVICES.git
        username: cjflores1
        shallow_clone: false
        auto_update: true
        branch: task9-cj
        encrypted_password: AES:csjDYJSI0Qvv4z56FRSwpw==:Uqm5myeRMLopOroovCee5Q==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                - world
                command: echo
                run_if: passed
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sonar-scanner comand h
                command: echo
                run_if: passed